import Head from 'next/head';
import Banner from '../components/banner/banner';
import NavBar from '../components/navbar/navbar';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <NavBar username='aymeric@hotmail.com' />
      <Banner
        title='Clifford the red dog'
        subTitle='Very cute dog'
        imgUrl='/static/clifford.webp'
      />

      {/*<NavBar />
      

  <Card />*/}
    </div>
  );
}
