import Head from 'next/head';
import Banner from '../components/banner/banner';
import SectionCards from '../components/card/section-cards';
import NavBar from '../components/navbar/navbar';
import styles from '../styles/Home.module.css';

import { getVideos } from '../lib/video';

export default function Home() {
  const disneyVideos = getVideos();

  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <NavBar username='aymeric@hotmail.com' />
      <Banner
        title='Clifford the red dog'
        subTitle='Very cute dog'
        imgUrl='/static/clifford.webp'
      />

      <div className={styles.sectionWrapper}>
        <SectionCards title='Disney' videos={disneyVideos} size='large' />
        <SectionCards
          title='Productivity'
          videos={disneyVideos}
          size='medium'
        />
      </div>
    </div>
  );
}
